-- B. DIMENSIONES
CREATE OR REPLACE TABLE `cepreuni_bi.dim_tiempo` AS
SELECT DISTINCT 
    ABS(FARM_FINGERPRINT(CONCAT(CAST(ANIO_POSTULA AS STRING), '-', CAST(CICLO_POSTULA AS STRING)))) as id_tiempo,
    CONCAT(ANIO_POSTULA, '-', CICLO_POSTULA) as periodo,
    CAST(ANIO_POSTULA AS INT64) as anio,
    CAST(CICLO_POSTULA AS INT64) as ciclo
FROM `cepreuni_bi.cepre_uni` WHERE ANIO_POSTULA IS NOT NULL;

CREATE OR REPLACE TABLE `cepreuni_bi.dim_ubicacion` AS
SELECT DISTINCT 
    ABS(FARM_FINGERPRINT(CONCAT(DOMICILIO_DEPA, DOMICILIO_PROV, DOMICILIO_DIST))) as id_ubicacion,
    DOMICILIO_DEPA as departamento,
    DOMICILIO_PROV as provincia,
    CASE WHEN DOMICILIO_DEPA LIKE '%LIMA%' THEN 'LIMA METROPOLITANA' ELSE 'PROVINCIA' END as macro_zona
FROM `cepreuni_bi.cepre_uni` WHERE DOMICILIO_DIST IS NOT NULL;

CREATE OR REPLACE TABLE `cepreuni_bi.dim_especialidad` AS
SELECT DISTINCT 
    ABS(FARM_FINGERPRINT(ESPECIALIDAD)) as id_especialidad,
    ESPECIALIDAD as carrera
FROM `cepreuni_bi.cepre_uni` WHERE ESPECIALIDAD IS NOT NULL;
